##############################################
# Run configuration - Validate Classifications
##############################################

# --- General Settings ---
LOG_LEVEL: "INFO"   # Logging verbosity: {DEBUG, INFO, WARNING, ERROR, CRITICAL}

# --- Directory Paths (relative to Snakefile location) ---
# Should be static unless project structure changes
INPUT_DIR: "input"
OUTPUT_DIR: "output"
LOG_DIR: "logs"
GENOMES_DIR: "supporting_files/genomes"               # Directory containing the genomes to map against
INDEX_DIR_BBMAP: "bbmap_indices"                      # Subdirectory within 'outdir' for BBMap indexes
ENVS_DIR: "envs"

# --- Input File Patterns & Specifications ---
# Change these as needed
FASTQ_FILE_PATTERN: "fastq/taxID-{tax_id}_R{direction}.fq.gz"           # Pattern for input FASTQ files
MAPPING_SPECIFICATION: "supporting_files/mapping_specification.yaml"    # File mapping tax IDs to genome files

# --- Tool Parameters ---
# BBMap specific settings
BBMAP_MINID: 0.97               # Minimum identity for mapping
BBMAP_AMBIGUOUS: "toss"         # How to handle ambiguous mappings {best, toss, random, all}
BBMAP_PAIREDONLY: "t"           # Treat unpaired reads as unmapped {t, f}

# Optional: Add resource configurations if needed
BBMAP_INDEX_MEM: "4g"
# BBMAP_INDEX_THREADS: 8
BBMAP_MAP_MEM: "4g"
# BBMAP_MAP_THREADS: 8