# -- Cluster submission settings --
cluster:
    jobscript: "slurm-jobscript.sh"
    submitcmd: "sbatch {dependencies}"

# -- Concurrency --
# Maximum number of jobs submitted to SLURM at once
jobs: 200

# -- Default Resources (Applied to all rules unless overridden) --
default-resources:
  slurm_account: "naiss2024-5-147"
  slurm_partition: "shared"
  runtime: "01:00:00"   # Format: "HH:MM:SS", "HHh", or "MMm"
  mem_mb: 4000
  cpus_per_task: 4

# -- Rule-Specific Resources (Overrides defaults) --
set-resources:
  bbmap_index:
    runtime: "04:00:00"
    mem_mb: 20000
    cpus_per_task: 8

  bbmap_map_reads:
    runtime: "24:00:00"
    mem_mb: 20000
    cpus_per_task: 32

  samtools_sort:
    runtime: "02:00:00"
    cpus_per_task: 6

  samtools_index:
    runtime: "01:00:00"
    cpus_per_task: 1