# -- Cluster submission settings --
cluster:
    jobscript: "slurm-jobscript.sh"
    submitcmd: "sbatch {dependencies}"

# -- Concurrency --
# Maximum number of jobs submitted to SLURM at once
jobs: 200

# -- Default Resources (Applied to all rules unless overridden) --
default-resources:
  slurm_account: "naiss2025-5-154"
  slurm_partition: "shared"
  runtime: "1h"
  mem_mb: 4000
  cpus_per_task: 4

# -- Rule-Specific Resources (Overrides defaults) --
set-resources:
  bbmap_index:
    runtime: "30m"
    mem_mb: 22000
    cpus_per_task: 6

  bbmap_map_reads:
    runtime: "24h"
    mem_mb: 22000
    cpus_per_task: 16

  samtools_sort:
    runtime: "2h"
    cpus_per_task: 6

  mark_duplicates_sambamba:
    mem_mb: 16000 # Or reference config: "{SAMBAMBA_MARKDUP_MEM_MB}"
    runtime: "2h" # Or reference config
    cpus-per-task: "{SAMBAMBA_MARKDUP_THREADS}" # Match threads
  
  samtools_index:
    mem_mb: 2000
    runtime: "1h"
    cpus-per-task: "{SAMTOOLS_INDEX_THREADS}"