# -- Cluster submission settings --
cluster:
    jobscript: "../slurm-jobscript.sh"
    submitcmd: "sbatch {dependencies}"

# -- Concurrency --
# Maximum number of jobs submitted to SLURM at once
jobs: 200

# -- Default Resources (Applied to all rules unless overridden) --
default-resources:
  slurm_account: "hpc2n2025-006"
  slurm_partition: "shared"
  runtime: "1h"
  mem_mb: 4000
  cpus_per_task: 8

# -- Rule-Specific Resources (Overrides defaults) --
set-resources:
  classify_all_concatenated:
    partition: "memory"